AWSTemplateFormatVersion: "2010-09-09"


Parameters:
BucketName:
Type: String
Description: Nome global e único do bucket S3 para website estático
MinLength: 3
MaxLength: 63
AllowedPattern: "[a-z0-9][a-z0-9\-]*[a-z0-9]"


IndexDocument:
Type: String
Default: index.html
Description: Documento inicial do website S3


ErrorDocument:
Type: String
Default: error.html
Description: Documento de erro do website S3


Resources:
SiteBucket:
Type: AWS::S3::Bucket
Properties:
BucketName: !Ref BucketName
WebsiteConfiguration:
IndexDocument: !Ref IndexDocument
ErrorDocument: !Ref ErrorDocument
PublicAccessBlockConfiguration:
BlockPublicAcls: false
BlockPublicPolicy: false
IgnorePublicAcls: false
RestrictPublicBuckets: false
Tags:
- Key: Project
Value: dio-primeira-stack
- Key: Purpose
Value: static-website


SiteBucketPolicy:
Type: AWS::S3::BucketPolicy
Properties:
Bucket: !Ref SiteBucket
PolicyDocument:
Version: "2012-10-17"
Statement:
- Sid: AllowPublicRead
Effect: Allow
Principal: "*"
Action: "s3:GetObject"
Resource: !Sub "${SiteBucket.Arn}/*"


Outputs:
WebsiteURL:
Description: URL do website estático hospedado no S3
Value: !GetAtt SiteBucket.WebsiteURL


BucketDomainName:
Description: Endpoint do bucket
Value: !GetAtt SiteBucket.DomainName
