AWSTemplateFormatVersion: "2010-09-09"
Description: >-
DIO – Template básico que cria um bucket S3 privado com bloqueio de acesso público ativado.



Metadata:
TemplateName: template-basic-s3
Version: 1.0.0


Parameters:
BucketName:
Type: String
Description: Nome global e único do bucket S3
MinLength: 3
MaxLength: 63
AllowedPattern: "[a-z0-9][a-z0-9\-]*[a-z0-9]"
ConstraintDescription: "Use apenas letras minúsculas, números e hífens; não comece/termine com hífen."


EnableVersioning:
Type: String
Default: "false"
AllowedValues: ["true", "false"]
Description: Ativa versionamento no bucket se "true".


Mappings:
VersioningStatusMap:
true:
Status: Enabled
false:
Status: Suspended


Resources:
S3Bucket:
Type: AWS::S3::Bucket
Properties:
BucketName: !Ref BucketName
PublicAccessBlockConfiguration:
BlockPublicAcls: true
BlockPublicPolicy: true
IgnorePublicAcls: true
RestrictPublicBuckets: true
VersioningConfiguration:
Status: !FindInMap [VersioningStatusMap, !Ref EnableVersioning, Status]
Tags:
- Key: Project
Value: dio-primeira-stack
- Key: ManagedBy
Value: cloudformation


Outputs:
BucketNameOut:
Description: Nome do bucket criado
Value: !Ref S3Bucket
Export:
Name: !Sub "${AWS::StackName}-BucketName"


BucketArn:
Description: ARN do bucket
Value: !GetAtt S3Bucket.Arn
Export:
Name: !Sub "${AWS::StackName}-BucketArn"
